name: Build CodeApp IPA

on:
  workflow_dispatch: # Chạy thủ công bằng nút bấm

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Frameworks
        run: |
          chmod +x ./downloadFrameworks.sh
          ./downloadFrameworks.sh

      - name: Build and Package IPA
        run: |
          xcodebuild build \
            -project Code.xcodeproj \
            -scheme "CodeUI" \
            -destination "generic/platform=iOS" \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r CodeApp.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa-build
          path: CodeApp.ipa
